# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  timeout: 5000
  adapter: mysql2
  pool: 5


development:
  database: event_app_development
  username: root
  <<: *default

test:
  database: event_app_test
  username: root
  <<: *default

production:
  <<: *default
